set hlsearch
set ruler
syntax on
set number
filetype on
filetype plugin on

" Tabs are not easy to handle it is better
" to stick to an easy scenario
" @ts tabstop, @sts softtabstop @sw shiftwidth
set ts=2 sts=2 sw=2 expandtab

set textwidth=80

function! Skeleton(file)
if a:file =~ '.*_test\.py$'
    keepalt 0r ~/.vim/skel/template_test.py
elseif a:file =~ '.*\.py$'
    keepalt 0r ~/.vim/skel/template.py
endif
endfunction
au BufNewFile *.py  :call Skeleton(expand("<afile>"))

au FileType xml setlocal foldmethod=syntax
au FileType java setlocal foldmethod=syntax

" Shortcut to rapidly toggle `set list`,
" " set list! used to show invisible characters
nmap <leader>l :set list!<CR>

" Use the same symbols as TextMate for tabstops and EOL
set listchars=tab:▸\ ,eol:¬
